import sys
import numpy as np

MOD = 998244353

# ---------------------------------------------------------------------------
# 13-state relation automaton.
#
# Cycle-orientation variables x_i in {0,1}: edge {i,i+1} contributes to the
# in-degree of i+1 iff x_i = 1, so the cycle edges give vertex i a base
# in-degree b_i = x_{i-1} + 1 - x_i.  A spoke at i (s_i = 1) adds y_i in
# {0,1}.  Hence c_i = d_i = b_i + y_i, and d_N is determined by the rest
# (total in-degree equals the number of edges), so the answer is the number
# of distinct words c = (c_0..c_{N-1}) realizable by some cyclic x.
#
# Reading c_i composes the current relation R ⊆ {0,1}x{0,1} of achievable
# (x_0, x_i) pairs with a fixed boolean relation:
#   s_i = 0: c = 0,1,2  ->  A, I, B
#   s_i = 1: c = 0,1,2,3 ->  A, U, V, B
# The monoid generated by {A, B, I, U, V} has exactly 13 elements
# {0, I, A, B, E0, E1, R0, R1, C0, C1, U, V, J} (closed under composition).
# Start at R = I; the word is achievable iff the final relation contains
# (0,0) or (1,1) (the cycle closes), i.e. R not in {0, A, B}.
# The subset construction is deterministic, so summing the word counts over
# accepting relations counts each distinct c (each distinct degree
# sequence) exactly once.
# ---------------------------------------------------------------------------

def rel_mul(p, q):
    r = 0
    for i in range(2):
        for j in range(2):
            for k in range(2):
                if (p >> (2 * i + k)) & 1 and (q >> (2 * k + j)) & 1:
                    r |= 1 << (2 * i + j)
                    break
    return r

ZERO = 0b0000
IID  = 0b1001
A    = 0b0010
B    = 0b0100
E0   = 0b0001
E1   = 0b1000
R0   = 0b0011
R1   = 0b1100
C0   = 0b0101
C1   = 0b1010
U    = 0b1011
V    = 0b1101
J    = 0b1111

BITS = [ZERO, IID, A, B, E0, E1, R0, R1, C0, C1, U, V, J]
IDX = {b: i for i, b in enumerate(BITS)}
NST = 13
# Accepting = relation contains (0,0) or (1,1); only 0, A, B reject.
ACC_NP = np.array([0 if b in (ZERO, A, B) else 1 for b in BITS],
                  dtype=np.int64)

T_S0 = [A, IID, B]      # c = 0,1,2   when s_i = 0
T_S1 = [A, U, V, B]     # c = 0,1,2,3 when s_i = 1

def build_step_matrix(Ts):
    M = np.zeros((NST, NST), dtype=np.int64)
    for st in range(NST):
        for T in Ts:
            M[st, IDX[rel_mul(BITS[st], T)]] += 1
    return M

STEP = (build_step_matrix(T_S0), build_step_matrix(T_S1))

CHUNK = 12
_chunk_cache = {}

def chunk_matrix(length, pattern):
    """Product STEP[bit_0] @ ... @ STEP[bit_{length-1}] (mod MOD), memoized."""
    key = (length, pattern)
    M = _chunk_cache.get(key)
    if M is None:
        if length == 1:
            M = STEP[pattern & 1]
        else:
            h = length >> 1
            M = np.dot(chunk_matrix(h, pattern & ((1 << h) - 1)),
                       chunk_matrix(length - h, pattern >> h)) % MOD
        _chunk_cache[key] = M
    return M

def solve(N, s):
    v = np.zeros(NST, dtype=np.int64)
    v[IDX[IID]] = 1
    nfull, rem = divmod(N, CHUNK)
    bits = [1 if c == 49 else 0 for c in s]
    for c in range(nfull):
        pat = 0
        base = c * CHUNK
        for j in range(CHUNK):
            pat |= bits[base + j] << j
        P = chunk_matrix(CHUNK, pat)
        # int64 overflow guard: entries < MOD ~ 1e9, so split the 13
        # columns 7+6; each partial dot stays < 7*MOD^2 < 2^63.
        r1 = np.dot(v, P[:, :7])
        r2 = np.dot(v, P[:, 7:])
        v = np.concatenate((r1, r2)) % MOD
    if rem:
        pat = 0
        base = nfull * CHUNK
        for j in range(rem):
            pat |= bits[base + j] << j
        P = chunk_matrix(rem, pat)
        r1 = np.dot(v, P[:, :7])
        r2 = np.dot(v, P[:, 7:])
        v = np.concatenate((r1, r2)) % MOD
    return int(np.dot(v, ACC_NP) % MOD)

def main():
    data = sys.stdin.buffer.read().split()
    N = int(data[0])
    s = data[1].decode()
    sys.stdout.write(str(solve(N, s)) + "\n")

main()