import sys

# Increase recursion depth just in case, though not needed for this iterative solution
sys.setrecursionlimit(2000)

def solve():
    # Read all input from stdin
    input_data = sys.stdin.read().split()
    
    if not input_data:
        return

    # Parse N and the string s
    N = int(input_data[0])
    s = input_data[1]
    
    MOD = 998244353
    
    # Count the number of '1's in the string s
    # These correspond to edges connecting cycle vertices to vertex N
    count_ones = s.count('1')
    
    # The problem asks for the number of distinct in-degree sequences (d_0, ..., d_N).
    # The graph consists of a cycle C_N on vertices 0..N-1 and edges from some cycle vertices to N.
    #
    # Let's analyze the cycle part first.
    # For the cycle, let u_i be 1 if edge (i, i+1) is oriented i->i+1, else 0.
    # The in-degree of vertex i from the cycle is d_i^cycle = (1 - u_{i-1}) + u_i (indices mod N).
    # The mapping from u in {0,1}^N to d^cycle is linear.
    # d_i^cycle = 1 + u_i - u_{i-1}.
    # Two orientations u and v produce the same d^cycle if u_i - u_{i-1} = v_i - v_{i-1} for all i.
    # This implies u_i - v_i = k (constant). Since u, v in {0,1}, k can be 0, 1, or -1.
    # If k=0, u=v.
    # If k=1, v = u - 1. This requires u to be all 1s and v to be all 0s.
    # If k=-1, v = u + 1. This requires u to be all 0s and v to be all 1s.
    # Thus, the only collision in the cycle part is between the all-0 orientation and the all-1 orientation.
    # Both produce d^cycle = (1, 1, ..., 1).
    # The number of distinct sequences generated by the cycle alone is 2^N - 1.
    
    # Now consider the edges to N.
    # For each i where s_i = 1, there is an edge (i, N).
    # Let x_i be 1 if i->N, 0 if N->i.
    # Then d_i = d_i^cycle + (1 - x_i) for i in S (where S is set of indices with s_i=1).
    # And d_N = sum(x_i).
    #
    # The key question is whether different cycle orientations combined with different x choices
    # can produce the same full sequence (d_0, ..., d_N).
    #
    # Case 1: u and v are distinct cycle orientations that produce DIFFERENT d^cycle.
    # Then for the full sequences to be equal, we must have d_i^cycle + (1-x_i) = d_i^v + (1-x'_i) for all i.
    # For i NOT in S, d_i = d_i^cycle. So we must have d_i^cycle = d_i^v.
    # But we assumed they produce different d^cycle. Contradiction.
    # So distinct d^cycle sequences lead to distinct full sequences regardless of x.
    #
    # Case 2: u and v are the colliding pair (all-0 and all-1).
    # They produce the SAME d^cycle = (1, 1, ..., 1).
    # So d_i^cycle = d_i^v for all i.
    # The full sequence depends on x.
    # d_i = 1 + (1-x_i) = 2 - x_i for i in S.
    # d_i = 1 for i not in S.
    # d_N = sum(x_i).
    # The sequence is determined entirely by the choice of x.
    # Since u and v produce the same d^cycle, they map to the same set of full sequences generated by x.
    # Specifically, for a fixed x, both u and v produce the same full sequence.
    # So the pair {u, v} contributes exactly 2^|S| distinct sequences (one for each x), not 2 * 2^|S|.
    #
    # All other 2^N - 2 orientations produce unique d^cycle sequences.
    # Each of these produces 2^|S| distinct full sequences (by varying x).
    #
    # Total count = (Number of distinct d^cycle sequences) * 2^|S|
    #             = (2^N - 1) * 2^|S|.
    
    # Calculate 2^N mod MOD
    pow2N = pow(2, N, MOD)
    
    # Calculate (2^N - 1) mod MOD
    term1 = (pow2N - 1 + MOD) % MOD
    
    # Calculate 2^count_ones mod MOD
    term2 = pow(2, count_ones, MOD)
    
    # Result is term1 * term2 mod MOD
    ans = (term1 * term2) % MOD
    
    print(ans)

if __name__ == '__main__':
    solve()