class Solution:
    def minCostGoodCaption(self, caption: str) -> str:
        n = len(caption)
        if n < 3:
            return ""
        
        # Precompute medians and costs for length 3
        # med3[i] stores the median character for caption[i:i+3]
        # cost3[i] stores the cost to convert caption[i:i+3] to that median
        med3 = [0] * (n - 2)
        cost3 = [0] * (n - 2)
        for i in range(n - 2):
            chars = [ord(caption[i]), ord(caption[i+1]), ord(caption[i+2])]
            chars.sort()
            m = chars[1]
            med3[i] = chr(m)
            cost3[i] = abs(ord(caption[i]) - m) + abs(ord(caption[i+1]) - m) + abs(ord(caption[i+2]) - m)
        
        # Precompute for length 4
        # For even length, pick the smaller median (index 1 in sorted list of 4) for lexicographical smallest result
        med4 = [0] * (n - 3)
        cost4 = [0] * (n - 3)
        for i in range(n - 3):
            chars = [ord(caption[i]), ord(caption[i+1]), ord(caption[i+2]), ord(caption[i+3])]
            chars.sort()
            # For 4 elements, sorted indices are 0, 1, 2, 3.
            # Medians are any value in [chars[1], chars[2]].
            # To minimize the resulting character lexicographically, we pick chars[1].
            m = chars[1] 
            med4[i] = chr(m)
            cost4[i] = abs(ord(caption[i]) - m) + abs(ord(caption[i+1]) - m) + abs(ord(caption[i+2]) - m) + abs(ord(caption[i+3]) - m)
            
        # Precompute for length 5
        med5 = [0] * (n - 4)
        cost5 = [0] * (n - 4)
        for i in range(n - 4):
            chars = [ord(caption[i]), ord(caption[i+1]), ord(caption[i+2]), ord(caption[i+3]), ord(caption[i+4])]
            chars.sort()
            m = chars[2]
            med5[i] = chr(m)
            cost5[i] = sum(abs(ord(caption[i+k]) - m) for k in range(5))
            
        # Prefix sums for cost3 at indices 0, 3, 6...
        # P3[k] = sum of cost3[0] + cost3[3] + ... + cost3[3*(k-1)]
        num_3_blocks = n // 3
        P3 = [0] * (num_3_blocks + 1)
        for i in range(num_3_blocks):
            P3[i+1] = P3[i] + cost3[3*i]
            
        min_total_cost = float('inf')
        candidates = []
        
        # Case 1: n % 3 == 0 -> All blocks of size 3
        if n % 3 == 0:
            total = P3[num_3_blocks]
            if total < min_total_cost:
                min_total_cost = total
                candidates.append(0) # 0 indicates no special block
            elif total == min_total_cost:
                candidates.append(0)
                
        # Case 2: n % 3 == 1 -> One block of size 4, rest size 3
        if n % 3 == 1:
            total_blocks = num_3_blocks
            # Iterate j from 0 to n-4 with step 3
            for j in range(0, n - 3, 3):
                if j + 4 > n:
                    break
                # Blocks before j: indices 0, 3, ..., j-3. Count = j//3.
                # Blocks after j+4: indices j+4, j+7, ...
                # Number of 3-blocks used before = j//3
                # Number of 3-blocks remaining = total_blocks - (j//3 + 1)
                # Sum before = P3[j//3]
                # Sum after = P3[total_blocks] - P3[j//3 + 1]
                
                cost_before = P3[j//3]
                cost_after = P3[total_blocks] - P3[j//3 + 1]
                current_cost = cost_before + cost4[j] + cost_after
                
                if current_cost < min_total_cost:
                    min_total_cost = current_cost
                    candidates = [j]
                elif current_cost == min_total_cost:
                    candidates.append(j)
                    
        # Case 3: n % 3 == 2 -> One block of size 5, rest size 3
        if n % 3 == 2:
            total_blocks = num_3_blocks
            for j in range(0, n - 4, 3):
                if j + 5 > n:
                    break
                cost_before = P3[j//3]
                cost_after = P3[total_blocks] - P3[j//3 + 1]
                current_cost = cost_before + cost5[j] + cost_after
                
                if current_cost < min_total_cost:
                    min_total_cost = current_cost
                    candidates = [j]
                elif current_cost == min_total_cost:
                    candidates.append(j)
                    
        if not candidates:
            return ""
            
        # Find lexicographically smallest among candidates
        best_j = candidates[0]
        for j in candidates[1:]:
            # Compare string generated by best_j and j
            # We compare character by character starting from min(best_j, j)
            # The strings are identical before min(best_j, j) and after max(best_j, j) + 5
            start_idx = min(best_j, j)
            end_idx = max(best_j, j) + 5
            
            # Helper to get char at index k for candidate j
            def get_char(k, cand_j):
                if cand_j == 0: # No special block
                    return med3[k//3]
                else:
                    offset = 5 if n % 3 == 2 else 4
                    if k < cand_j:
                        return med3[k//3]
                    elif k < cand_j + offset:
                        return med4[cand_j] if n % 3 == 1 else med5[cand_j]
                    else:
                        return med3[k//3]
            
            # Compare
            for k in range(start_idx, end_idx):
                c1 = get_char(k, best_j)
                c2 = get_char(k, j)
                if c1 < c2:
                    break # best_j is smaller
                elif c1 > c2:
                    best_j = j # j is smaller
                    break
            else:
                # If loop completes without break, strings are identical in this range
                # Since they differ only in this range, they are identical strings.
                # We can keep best_j.
                pass
        
        # Construct the result string
        res = []
        offset = 5 if n % 3 == 2 else 4
        if best_j == 0:
            for i in range(num_3_blocks):
                res.append(med3[3*i])
        else:
            # Before special block
            for i in range(best_j):
                res.append(med3[i//3])
            # Special block
            if n % 3 == 1:
                res.append(med4[best_j])
            else:
                res.append(med5[best_j])
            # After special block
            for i in range(best_j + offset, n):
                res.append(med3[i//3])
                
        return "".join(res)