import sys

# Increase recursion depth just in case, though this solution is iterative.
sys.setrecursionlimit(2000)

def solve():
    # Read all input from standard input
    input_data = sys.stdin.read().split()
    
    if not input_data:
        return

    N = int(input_data[0])
    s_str = input_data[1]
    
    MOD = 998244353
    
    # Count the number of 1s in the string s.
    # This corresponds to the number of spoke edges connected to vertex N.
    K = s_str.count('1')
    
    # Precompute factorials and inverse factorials for O(1) combination queries.
    # We need factorials up to N.
    fact = [1] * (N + 1)
    inv = [1] * (N + 1)
    
    for i in range(1, N + 1):
        fact[i] = (fact[i-1] * i) % MOD
        
    # Fermat's Little Theorem for modular inverse since MOD is prime
    inv[N] = pow(fact[N], MOD - 2, MOD)
    for i in range(N - 1, -1, -1):
        inv[i] = (inv[i+1] * (i + 1)) % MOD
        
    def nCr_mod(n, r):
        if r < 0 or r > n:
            return 0
        num = fact[n]
        den = (inv[r] * inv[n-r]) % MOD
        return (num * den) % MOD
    
    # Calculate the number of distinct Z sequences generated by the cycle edges.
    # The sequence Z is determined by the transitions in the cycle orientation x.
    # z_i = 2 corresponds to a 0->1 transition, z_i = 0 to a 1->0 transition.
    # In a cycle, the number of 0->1 transitions (k) must equal the number of 1->0 transitions.
    #
    # Case k=0: No transitions. x is all 0s or all 1s. Both yield Z=(1, 1, ..., 1).
    # This contributes 1 distinct sequence.
    #
    # Case k >= 1: We choose k positions for '2's and k positions for '0's from the remaining N-k spots.
    # The number of ways is C(N, k) * C(N-k, k).
    # Each such configuration yields a unique Z sequence.
    
    distinct_Z_count = 1 # For k=0 case
    
    limit = N // 2
    for k in range(1, limit + 1):
        # Calculate C(N, k)
        c1 = nCr_mod(N, k)
        # Calculate C(N-k, k)
        c2 = nCr_mod(N - k, k)
        
        term = (c1 * c2) % MOD
        distinct_Z_count = (distinct_Z_count + term) % MOD
        
    # For each distinct Z sequence, there are 2^K ways to orient the spoke edges.
    # Since the full tuple includes d_i for all i, and changing a spoke orientation
    # changes at least one d_i (specifically d_i and d_N), all 2^K choices produce
    # distinct full tuples for a fixed Z.
    # Total Answer = distinct_Z_count * 2^K
    
    ans = (distinct_Z_count * pow(2, K, MOD)) % MOD
    
    print(ans)

if __name__ == '__main__':
    solve()